{
 "title": "Local Storage Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(local_storage_pv_capacity_bytes,node_name)"
    }
   },
   {
    "name": "storageClassName",
    "label": "Storage Class",
    "query": {
     "query": "label_values(local_storage_pv_capacity_bytes{node_name=~\"$node\"},storage_class_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(local_storage_pv_capacity_bytes{node_name=~\"$node\", storage_class_name=~\"$storageClassName\"},pvc_namespace)"
    }
   },
   {
    "name": "pvc",
    "label": "PersistentVolumeClaim",
    "query": {
     "query": "label_values(local_storage_pv_capacity_bytes{node_name=~\"$node\", storage_class_name=~\"$storageClassName\", pvc_namespace=~\"$namespace\"},pvc_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mounted Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "local_storage_mounted_disk_used_bytes{node_name=~\"$node\"}",
     "legendFormat": "Used Space: {{node_name}}"
    },
    {
     "expr": "local_storage_mounted_disk_capacity_bytes{node_name=~\"$node\"}",
     "legendFormat": "Capacity: {{node_name}}"
    }
   ]
  },
  {
   "title": "Mounted Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "local_storage_mounted_disk_used_bytes{node_name=~\"$node\"} / local_storage_mounted_disk_capacity_bytes{node_name=~\"$node\"} * 100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "local_storage_pv_used_bytes{pvc_namespace=~\"$namespace\", pvc_name=~\"$pvc\"}",
     "legendFormat": "PV Used Space: {{pvc_name}}"
    }
   ]
  },
  {
   "title": "PV Space Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(local_storage_pv_used_bytes /on(node_name) group_left() local_storage_mounted_disk_capacity_bytes * 100)",
     "legendFormat": "{{pvc_name}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "local_storage_pv_used_bytes{node=~\"$node\", storage_class_name=~\"$storageClassName\", pvc_namespace=~\"$namespace\", pvc_name=~\"$pvc\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "local_storage_pv_used_bytes{node=~\"$node\", storage_class_name=~\"$storageClassName\", pvc_namespace=~\"$namespace\", pvc_name=~\"$pvc\"} /on(node_name) group_left() local_storage_mounted_disk_capacity_bytes{node_name=~\"$node\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}