apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: local-storage-exporter-podmonitor
spec:
  selector:
    matchLabels:
      app: local-storage-exporter
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    any: true