{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-local-storage-exporter-servicemonitor
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-local-storage-exporter
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{ end }}